FROM pytroll_base_image

RUN . /root/.bashrc && \
    mamba install -y satpy \
    pyresample \
    pykdtree \
    trollimage \
    pycoast \
    pyorbital \
    rasterio \
    gdal \
    h5py \
    ipython \
    pyinotify \
    pyzmq \
    h5netcdf \
    netifaces \
    meld3 \
    scp \
    paramiko \
    dpath \
    toolz \
    configobj \
    pip \
    git && \
    mamba install -y -c eumetsat public-decomp-wt && \
    mamba clean -a -y

ADD requirements_stable.txt /tmp/
RUN . /root/.bashrc && \
    pip install -r /tmp/requirements_stable.txt && \
    rm -r /tmp/requirements_stable.txt &&  \
    cd /tmp/ && \
    git clone https://github.com/Supervisor/supervisor.git && \
    cd supervisor && python setup.py install && \
    cd /tmp/ && rm -rf /tmp/supervisor/ && \
    git clone https://github.com/Supervisor/superlance.git && \
    cd superlance && python setup.py install && \
    cd /tmp/ && rm -rf /tmp/superlance/ && \
    #python -c 'from pyspectral.utils import download_luts; \
    #  from pyspectral.utils import logging_on; import logging; \
    #  logging_on(logging.DEBUG); download_luts()' && \
    #python -c 'from pyspectral.utils import download_rsr; \
    #  from pyspectral.utils import logging_on; import logging; \
    #  logging_on(logging.DEBUG); download_rsr()' && \
    #mkdir -p /home/user/.local/share && \
    #mv /root/.local/share/pyspectral /home/user/.local/share/ && \
    pip cache purge && \
    mamba uninstall -y git && \
    mamba clean -a -y

COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
