# Use a Python image with uv pre-installed
FROM ghcr.io/astral-sh/uv:python3.13-trixie-slim


RUN apt-get update && apt-get install -y --no-install-recommends \
    gdal \
 && rm -rf /var/lib/apt/lists/*

# Setup a non-root user
RUN addgroup --system --gid 1000 nonroot \
 && adduser --system --uid 1000 --ingroup nonroot --no-create-home nonroot
WORKDIR /db-push

# Enable bytecode compilation
ENV UV_COMPILE_BYTECODE=1

# Copy from the cache instead of linking since it's a mounted volume
ENV UV_LINK_MODE=copy

# Ensure installed tools can be executed out of the box
ENV UV_TOOL_BIN_DIR=/usr/local/bin

ENV APP_DIR=/db-push
RUN mkdir -p $APP_DIR

# set working directory
WORKDIR $APP_DIR

# copy main files
COPY db_push.py $APP_DIR

# Install the project's dependencies using the lockfile and settings
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --locked --no-install-project --no-dev

# Place executables in the environment at the front of the path
ENV PATH="$APP_DIR/.venv/bin:$PATH"

# Use the non-root user to run our application
USER nonroot

# COPY entrypoint.sh /usr/bin/
# RUN chmod +x /usr/bin/entrypoint.sh
# ENTRYPOINT ["/usr/bin/entrypoint.sh"]
ENTRYPOINT []

CMD ["python", "$APP_DIR/db_push.py", "/config/db-push.yaml", "/etc/trollflow2.yaml"]
