FROM registry.access.redhat.com/ubi8/ubi-minimal

RUN microdnf update && \
    microdnf install shadow-utils && \
    microdnf clean all

ENV GOSU_VERSION=1.11
RUN gpg --keyserver keys.openpgp.org --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 \
    && curl -o /usr/bin/gosu -SL "https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-amd64" \
    && curl -o /usr/bin/gosu.asc -SL "https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-amd64.asc" \
    && gpg --verify /usr/bin/gosu.asc \
    && rm /usr/bin/gosu.asc \
    && rm -r /root/.gnupg/ \
    && chmod +x /usr/bin/gosu \
    # Verify that the binary works
    && gosu nobody true

RUN curl -L -o Mambaforge-latest-Linux-x86_64.sh https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Linux-x86_64.sh && \
    sh Mambaforge-latest-Linux-x86_64.sh -b -p /opt/conda && \
    rm Mambaforge-latest-Linux-x86_64.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> /root/.bashrc && \
    echo "conda activate base" >> /root/.bashrc && \
    source /root/.bashrc && \
    mamba update -n base conda && \
    mamba update --all && \
    mamba clean -a -y
