FROM ubuntu:latest

RUN apt-get update && apt-get -y --no-install-recommends install \
    gosu \
    curl \
    ca-certificates

RUN curl -L -o Mambaforge-latest-Linux-x86_64.sh https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Linux-x86_64.sh && \
    sh Mambaforge-latest-Linux-x86_64.sh -b -p /opt/conda && \
    rm Mambaforge-latest-Linux-x86_64.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> /root/.bashrc && \
    echo "conda activate base" >> /root/.bashrc && \
    . /root/.bashrc && \
    mamba update -n base conda && \
    mamba update --all
