FROM docker.io/python:3.10

ENV APP_DIR=/usr/local/bin/db-sync
RUN mkdir $APP_DIR

# Copy pip to use pinned down versions
COPY requirements_stable.txt      $APP_DIR/

# set working directory
WORKDIR $APP_DIR

# change file ownership
RUN chmod -R +x $APP_DIR

# copy main files
COPY db-sync.py $APP_DIR

RUN pip install -r requirements_stable.txt && \
    rm -r requirements_stable.txt

COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh


ENTRYPOINT ["/usr/bin/entrypoint.sh"]
