FROM docker.io/python:3.10

ENV APP_DIR=/usr/local/bin/db-sync
RUN mkdir $APP_DIR

# Copy pip to use pinned down versions
COPY requirements_stable.txt      $APP_DIR/

# set working directory
WORKDIR $APP_DIR

# change file ownership
RUN chmod -R +x $APP_DIR

# copy main file
COPY . $APP_DIR

RUN pip install -r requirements_stable.txt && \
    rm -r requirements_stable.txt

ENTRYPOINT [ "/usr/bin/python ${APP_DIR}/db-sync.py ${APP_DIR}/db-sync.yaml /etc/trollflow2.yaml" ]
