FROM pytroll_base_image

RUN . /root/.bashrc && \
    mamba install -c conda-forge \
    pyinotify \
    trollsift \
    netifaces \
    pyzmq \
    six \
    scp \
    paramiko \
    pyyaml \
    watchdog \
    pip \
    git \
    && \
    conda clean -a -y

ADD requirements_stable.txt /tmp/
RUN . /root/.bashrc && \
    pip install -r /tmp/requirements_stable.txt && \
    rm -r /tmp/requirements_stable.txt &&  \
    cd /tmp/ && \
    git clone https://github.com/pytroll/posttroll.git && \
    cd posttroll && pip install . && \
    cd /tmp/ && rm -rf /tmp/posttroll && \
    git clone https://github.com/pytroll/trollmoves.git && \
    cd trollmoves && pip install . && \
    cd /tmp/ && rm -rf /tmp/trollmoves && \
    git clone https://github.com/Supervisor/supervisor.git && \
    cd supervisor && pip install . && \
    cd /tmp/ && rm -rf /tmp/supervisor/ && \
    git clone https://github.com/Supervisor/superlance.git && \
    cd superlance && pip install . && \
    cd /tmp/ && rm -rf /tmp/superlance/

COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
